export enum Action {
  LOADING_LOTES,
  SAVE_LOTES,
  ADD_LOTE,
  REMOVE_LOTE,
  // Guardia
  ADD_GUARDIA,
  REMOVE_GUARDIA,
  LOADING_GUARDIA,
  // Propietario
  ADD_PROPIETARIO,
  REMOVE_PROPIETARIO,
  LOADING_PROPIETARIOS,
  SAVE_PROPIETARIOS,
}
